### ISSUE TITLE
Nova install creates './~/.nova/' directory structure in current directory

### ISSUE THREAD

**Issue by barryoneill** [gilt/nova#31]
The setup script is incorrectly resolving the user's home directory, and instead creates the .nova dir in a folder called '~' wherever the setup script is called.  

In the case of a pip install, this will result in `/usr/local/~/.nova` being created.

**Comment by barryoneill** [comment]
Resolved with https://github.com/gilt/nova/pull/32

**Comment by barryoneill** [comment]
Resolved with https://github.com/gilt/nova/pull/32

**Comment by gheine** [comment]
Released in v11.0.5
