### ISSUE TITLE
Document or help with setting up an AMI with required features

### ISSUE THREAD

**Issue by fiadliel** [gilt/nova#5]
The default AMI for nova is not public, so an AMI with (at least) CodeDeploy is required, and probably Cloudwatch Logs.

Documentation on how this should be set up would be useful.

Ability to set up the integration by automating details from http://docs.aws.amazon.com/codedeploy/latest/userguide/auto-scaling-integ-tutorial.html might be interesting too (at least an ability to specify the `instance-setup.sh` script to run on installation).

**Comment by gheine** [comment]
👍

**Comment by grahamar** [comment]
Documented here - http://gilt-nova.readthedocs.io/en/latest/getting_started.html#instance-prerequisites
